FROM __SRC_IMAGE__
RUN set -eux; \
    apk update; \
    apk add --no-cache \
        build-base \
        clang \
        postgresql-dev \
        git; \
    git clone --depth 1 --branch v0.8.0 https://github.com/pgvector/pgvector.git /tmp/pgvector; \
    cd /tmp/pgvector; \
    make OPTFLAGS=""; \
    make install; \
    cd /; \
    rm -rf /tmp/pgvector; \
    apk del build-base clang postgresql-dev git; \
    rm -rf /var/cache/apk/*
